# Generated by Django 5.1.3 on 2024-12-04 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 17, 35, 19, 119173, tzinfo=datetime.timezone.utc)),
        ),
    ]
