# Generated by Django 5.1.3 on 2024-12-05 18:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 18, 3, 45, 964783, tzinfo=datetime.timezone.utc)),
        ),
    ]
