# Generated by Django 5.1.4 on 2024-12-06 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.RenameField(
            model_name='coursecontent',
            old_name='uploded_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 17, 8, 59, 783526, tzinfo=datetime.timezone.utc)),
        ),
    ]
