# Generated by Django 5.1.4 on 2024-12-06 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_coursecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 17, 9, 10, 313767, tzinfo=datetime.timezone.utc)),
        ),
    ]
