# Generated by Django 5.1.4 on 2024-12-06 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogress',
            old_name='last_wached_content',
            new_name='last_watched_content',
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 17, 37, 26, 447432, tzinfo=datetime.timezone.utc)),
        ),
    ]
