# Generated by Django 5.1.4 on 2024-12-06 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_quiz_course_quiz_course_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 19, 33, 41, 748512, tzinfo=datetime.timezone.utc)),
        ),
    ]
