# Generated by Django 5.1.4 on 2024-12-06 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_data_file',
            field=models.FileField(null=True, upload_to='course_contents/'),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 20, 1, 1, 236024, tzinfo=datetime.timezone.utc)),
        ),
    ]
