# Generated by Django 5.1.4 on 2024-12-06 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_coursecontent_content_data_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 20, 1, 6, 670861, tzinfo=datetime.timezone.utc)),
        ),
    ]
