# Generated by Django 5.1.4 on 2024-12-06 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='possible_answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_text',
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 20, 9, 39, 627113, tzinfo=datetime.timezone.utc)),
        ),
    ]
