# Generated by Django 5.1.4 on 2024-12-08 16:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='App.coursecontent'),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 16, 54, 59, 445150, tzinfo=datetime.timezone.utc)),
        ),
    ]
