# Generated by Django 5.1.4 on 2024-12-08 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_quiz_course_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 16, 55, 4, 437276, tzinfo=datetime.timezone.utc)),
        ),
    ]
