# Generated by Django 5.1.4 on 2024-12-08 22:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='topic',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to='App.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumpost',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 22, 30, 50, 525596, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
    ]
