# Generated by Django 5.1.4 on 2024-12-08 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_forumpost_topic_forumpost_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 22, 31, 34, 831107, tzinfo=datetime.timezone.utc)),
        ),
    ]
