# Generated by Django 5.1.4 on 2024-12-09 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpostcomment',
            old_name='Post',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 0, 18, 44, 114910, tzinfo=datetime.timezone.utc)),
        ),
    ]
