# Generated by Django 5.1.4 on 2024-12-14 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_studentsubscription_end_date_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 23, 7, 30, 801675, tzinfo=datetime.timezone.utc)),
        ),
    ]
