# Generated by Django 5.1.4 on 2024-12-17 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 22, 13, 6, 869591, tzinfo=datetime.timezone.utc)),
        ),
    ]
