# Generated by Django 5.1.4 on 2024-12-17 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_student_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 22, 14, 16, 564327, tzinfo=datetime.timezone.utc)),
        ),
    ]
