# Generated by Django 5.1.4 on 2024-12-17 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 23, 20, 29, 50275, tzinfo=datetime.timezone.utc)),
        ),
    ]
