# Generated by Django 5.1.4 on 2024-12-19 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogress',
            old_name='last_watched_content',
            new_name='watched_course_content_id',
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 22, 13, 52, 741395, tzinfo=datetime.timezone.utc)),
        ),
    ]
