# Generated by Django 5.1.4 on 2024-12-19 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_rename_last_watched_content_studentprogress_watched_course_content_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 22, 14, 3, 839699, tzinfo=datetime.timezone.utc)),
        ),
    ]
