# Generated by Django 5.1.4 on 2024-12-19 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_rename_watched_course_content_id_studentprogress_watched_course_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 22, 31, 19, 473990, tzinfo=datetime.timezone.utc)),
        ),
    ]
