# Generated by Django 5.1.4 on 2024-12-19 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 23, 18, 15, 325958, tzinfo=datetime.timezone.utc)),
        ),
    ]
