# Generated by Django 5.1.4 on 2024-12-19 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_alter_studentprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 23, 18, 21, 607941, tzinfo=datetime.timezone.utc)),
        ),
    ]
