# Generated by Django 5.1.4 on 2024-12-21 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certifications_image',
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 1, 30, 17, 52279, tzinfo=datetime.timezone.utc)),
        ),
    ]
