# Generated by Django 5.1.4 on 2024-12-21 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_remove_certificate_certifications_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 1, 30, 23, 104025, tzinfo=datetime.timezone.utc)),
        ),
    ]
