# Generated by Django 5.1.4 on 2024-12-21 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 15, 25, 54, 592975, tzinfo=datetime.timezone.utc)),
        ),
    ]
