# Generated by Django 5.1.4 on 2024-12-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
