# Generated by Django 5.1.4 on 2024-12-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_alter_studentsubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
