# Generated by Django 5.1.4 on 2024-12-29 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_remove_affiliateprogram_instructor_user_referalcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='boughted',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='earning',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='referal_link',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='refereduser',
            field=models.ManyToManyField(blank=True, related_name='refereduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='affiliatedusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boughted', models.BooleanField(default=False)),
                ('earning', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliateduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
