# Generated by Django 5.1.4 on 2024-12-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_remove_affiliation_boughted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='referal_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
