# Generated by Django 5.1.4 on 2024-12-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_alter_affiliation_referal_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliatedusers',
            old_name='user',
            new_name='affiliateduser',
        ),
        migrations.AddField(
            model_name='affiliatedusers',
            name='affiliation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='App.affiliation'),
            preserve_default=False,
        ),
    ]
