# Generated by Django 5.1.4 on 2025-01-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_rename_user_affiliatedusers_affiliateduser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_Order',
        ),
    ]
