# Generated by Django 5.1.4 on 2025-01-26 14:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_data_file',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='file'),
        ),
    ]
